language: php
php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4
  - 8.0

env:
  global:
    - XDEBUG_MODE=coverage
  matrix:
    - COMPOSER_FLAGS="--prefer-lowest"
    - COMPOSER_FLAGS=""

jobs:
  exclude:
    - php: 7.4
      env: COMPOSER_FLAGS="--prefer-lowest"
    - php: 8.0
      env: COMPOSER_FLAGS="--prefer-lowest"

before_script:
  - travis_retry composer self-update
  - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-dist

script:
  - vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover

after_script:
  - php vendor/bin/ocular code-coverage:upload --format=php-clover coverage.clover

cache:
 directories:
    - $HOME/.composer/cache/files
